/* Auto-generated by c_mutatedStages Architecture Synthesizer */
/* Unique Architecture ID: eBPF_Poly_VM_1d16dbcf23f9 */
/* Paradigm: HYBRID_STACK_REG | Dispatch: DISPATCH_DIRECT_THREADED */

#ifndef VM_EBPF_POLY_VM_1D16DBCF23F9_H
#define VM_EBPF_POLY_VM_1D16DBCF23F9_H

#include <stdint.h>
#include <stdbool.h>

#define ARCH_ID "eBPF_Poly_VM_1d16dbcf23f9"
#define PIPELINE_STAGE_COUNT 8

/* Opcodes for this polymorphic instance */
typedef enum {
    OP_HALT = 0,
    OP_INT_SBORROW = 1,
    OP_INT_SLESS = 2,
    OP_INT_REM = 3,
    OP_INT_SEXT = 4,
    OP_STORE = 5,
    OP_INT_EQUAL = 6,
    OP_CALL = 7,
    OP_INT_SUB = 8,
    OP_INT_CARRY = 9,
    OP_RETURN = 10
} eBPF_Poly_VM_1d16dbcf23f9_opcode_t;

/* Formal pipeline stage sequence */
typedef enum {
    STAGE_0_STAGE_FETCH,
    STAGE_1_STAGE_DYNAMIC_DECRYPT,
    STAGE_2_STAGE_JUNK_NOOP,
    STAGE_3_STAGE_DECODE,
    STAGE_4_STAGE_OPERAND_FETCH,
    STAGE_5_STAGE_STAGE_MUTATOR,
    STAGE_6_STAGE_EXECUTE,
    STAGE_7_STAGE_COMMIT_WRITEBACK
} eBPF_Poly_VM_1d16dbcf23f9_stage_t;

/* Latches / Inter-stage register state */
typedef struct {
    uint32_t pc;
    uint64_t registers[16];
    uint64_t stack[64];
    uint32_t sp;
    uint32_t current_stage_idx;
    uint32_t entropy_key;
    bool halted;
} eBPF_Poly_VM_1d16dbcf23f9_context_t;

#endif /* VM_EBPF_POLY_VM_1D16DBCF23F9_H */
