/* Auto-generated by c_mutatedStages Architecture Synthesizer */
/* Unique Architecture ID: eBPF_Poly_VM_9c016b71d0ea */
/* Paradigm: REGISTER | Dispatch: DISPATCH_CALL_THREADED */

#ifndef VM_EBPF_POLY_VM_9C016B71D0EA_H
#define VM_EBPF_POLY_VM_9C016B71D0EA_H

#include <stdint.h>
#include <stdbool.h>

#define ARCH_ID "eBPF_Poly_VM_9c016b71d0ea"
#define PIPELINE_STAGE_COUNT 7

/* Opcodes for this polymorphic instance */
typedef enum {
    OP_BPF_XOR = 0,
    OP_BPF_DIV = 1,
    OP_BPF_AND = 2,
    OP_BPF_MOD = 3,
    OP_BPF_NEG = 4,
    OP_BPF_MUL = 5,
    OP_BPF_ARSH = 6,
    OP_HALT = 7,
    OP_BPF_RSH = 8,
    OP_BPF_OR = 9,
    OP_BPF_SUB = 10
} eBPF_Poly_VM_9c016b71d0ea_opcode_t;

/* Formal pipeline stage sequence */
typedef enum {
    STAGE_0_STAGE_FETCH,
    STAGE_1_STAGE_DYNAMIC_DECRYPT,
    STAGE_2_STAGE_DECODE,
    STAGE_3_STAGE_OPERAND_FETCH,
    STAGE_4_STAGE_EXECUTE,
    STAGE_5_STAGE_JUNK_NOOP,
    STAGE_6_STAGE_COMMIT_WRITEBACK
} eBPF_Poly_VM_9c016b71d0ea_stage_t;

/* Latches / Inter-stage register state */
typedef struct {
    uint32_t pc;
    uint64_t registers[16];
    uint64_t stack[64];
    uint32_t sp;
    uint32_t current_stage_idx;
    uint32_t entropy_key;
    bool halted;
} eBPF_Poly_VM_9c016b71d0ea_context_t;

#endif /* VM_EBPF_POLY_VM_9C016B71D0EA_H */
