/* Auto-generated by c_mutatedStages Architecture Synthesizer */
/* Unique Architecture ID: RV_Metamorphic_VM_94bd3e05c3a2 */
/* Paradigm: REGISTER | Dispatch: DISPATCH_STAGED_COROUTINE */

#ifndef VM_RV_METAMORPHIC_VM_94BD3E05C3A2_H
#define VM_RV_METAMORPHIC_VM_94BD3E05C3A2_H

#include <stdint.h>
#include <stdbool.h>

#define ARCH_ID "RV_Metamorphic_VM_94bd3e05c3a2"
#define PIPELINE_STAGE_COUNT 7

/* Opcodes for this polymorphic instance */
typedef enum {
    OP_BPF_XOR = 0,
    OP_BPF_LSH = 1,
    OP_BPF_OR = 2,
    OP_BPF_NEG = 3,
    OP_BPF_DIV = 4,
    OP_BPF_AND = 5,
    OP_BPF_END = 6,
    OP_BPF_SUB = 7,
    OP_HALT = 8,
    OP_BPF_ARSH = 9,
    OP_BPF_MOD = 10
} RV_Metamorphic_VM_94bd3e05c3a2_opcode_t;

/* Formal pipeline stage sequence */
typedef enum {
    STAGE_0_STAGE_FETCH,
    STAGE_1_STAGE_DYNAMIC_DECRYPT,
    STAGE_2_STAGE_DECODE,
    STAGE_3_STAGE_OPERAND_FETCH,
    STAGE_4_STAGE_EXECUTE,
    STAGE_5_STAGE_STAGE_MUTATOR,
    STAGE_6_STAGE_COMMIT_WRITEBACK
} RV_Metamorphic_VM_94bd3e05c3a2_stage_t;

/* Latches / Inter-stage register state */
typedef struct {
    uint32_t pc;
    uint64_t registers[16];
    uint64_t stack[64];
    uint32_t sp;
    uint32_t current_stage_idx;
    uint32_t entropy_key;
    bool halted;
} RV_Metamorphic_VM_94bd3e05c3a2_context_t;

#endif /* VM_RV_METAMORPHIC_VM_94BD3E05C3A2_H */
