/* Auto-generated by c_mutatedStages Architecture Synthesizer */
/* Unique Architecture ID: RV_Metamorphic_VM_92b91413cfc5 */
/* Paradigm: HYBRID_STACK_REG | Dispatch: DISPATCH_DIRECT_THREADED */

#ifndef VM_RV_METAMORPHIC_VM_92B91413CFC5_H
#define VM_RV_METAMORPHIC_VM_92B91413CFC5_H

#include <stdint.h>
#include <stdbool.h>

#define ARCH_ID "RV_Metamorphic_VM_92b91413cfc5"
#define PIPELINE_STAGE_COUNT 6

/* Opcodes for this polymorphic instance */
typedef enum {
    OP_HALT = 0,
    OP_INT_EQUAL = 1,
    OP_INT_SEXT = 2,
    OP_INT_MULT = 3,
    OP_CBRANCH = 4,
    OP_INT_AND = 5,
    OP_RETURN = 6,
    OP_STORE = 7,
    OP_CALL = 8,
    OP_SUBPIECE = 9,
    OP_INT_REM = 10
} RV_Metamorphic_VM_92b91413cfc5_opcode_t;

/* Formal pipeline stage sequence */
typedef enum {
    STAGE_0_STAGE_FETCH,
    STAGE_1_STAGE_DYNAMIC_DECRYPT,
    STAGE_2_STAGE_DECODE,
    STAGE_3_STAGE_OPERAND_FETCH,
    STAGE_4_STAGE_EXECUTE,
    STAGE_5_STAGE_COMMIT_WRITEBACK
} RV_Metamorphic_VM_92b91413cfc5_stage_t;

/* Latches / Inter-stage register state */
typedef struct {
    uint32_t pc;
    uint64_t registers[16];
    uint64_t stack[64];
    uint32_t sp;
    uint32_t current_stage_idx;
    uint32_t entropy_key;
    bool halted;
} RV_Metamorphic_VM_92b91413cfc5_context_t;

#endif /* VM_RV_METAMORPHIC_VM_92B91413CFC5_H */
