/* Auto-generated by c_mutatedStages Architecture Synthesizer */
/* Unique Architecture ID: VM_Gen_3_e56eea9036ed */
/* Paradigm: REGISTER | Dispatch: DISPATCH_CALL_THREADED */

#ifndef VM_VM_GEN_3_E56EEA9036ED_H
#define VM_VM_GEN_3_E56EEA9036ED_H

#include <stdint.h>
#include <stdbool.h>

#define ARCH_ID "VM_Gen_3_e56eea9036ed"
#define PIPELINE_STAGE_COUNT 8

/* Opcodes for this polymorphic instance */
typedef enum {
    OP_BPF_MUL = 0,
    OP_BPF_MOV = 1,
    OP_BPF_OR = 2,
    OP_BPF_MOD = 3,
    OP_BPF_ADD = 4,
    OP_BPF_AND = 5,
    OP_BPF_LSH = 6,
    OP_HALT = 7,
    OP_BPF_SUB = 8,
    OP_BPF_NEG = 9,
    OP_BPF_XOR = 10
} VM_Gen_3_e56eea9036ed_opcode_t;

/* Formal pipeline stage sequence */
typedef enum {
    STAGE_0_STAGE_FETCH,
    STAGE_1_STAGE_JUNK_NOOP,
    STAGE_2_STAGE_DYNAMIC_DECRYPT,
    STAGE_3_STAGE_DECODE,
    STAGE_4_STAGE_JUNK_NOOP,
    STAGE_5_STAGE_OPERAND_FETCH,
    STAGE_6_STAGE_EXECUTE,
    STAGE_7_STAGE_COMMIT_WRITEBACK
} VM_Gen_3_e56eea9036ed_stage_t;

/* Latches / Inter-stage register state */
typedef struct {
    uint32_t pc;
    uint64_t registers[16];
    uint64_t stack[64];
    uint32_t sp;
    uint32_t current_stage_idx;
    uint32_t entropy_key;
    bool halted;
} VM_Gen_3_e56eea9036ed_context_t;

#endif /* VM_VM_GEN_3_E56EEA9036ED_H */
