/* Auto-generated by c_mutatedStages Architecture Synthesizer */
/* Unique Architecture ID: VM_Gen_3_bfaee9f8d108 */
/* Paradigm: HYBRID_STACK_REG | Dispatch: DISPATCH_STAGED_COROUTINE */

#ifndef VM_VM_GEN_3_BFAEE9F8D108_H
#define VM_VM_GEN_3_BFAEE9F8D108_H

#include <stdint.h>
#include <stdbool.h>

#define ARCH_ID "VM_Gen_3_bfaee9f8d108"
#define PIPELINE_STAGE_COUNT 9

/* Opcodes for this polymorphic instance */
typedef enum {
    OP_INT_SLESSEQUAL = 0,
    OP_CALL = 1,
    OP_INT_RIGHT = 2,
    OP_INT_NOTEQUAL = 3,
    OP_INT_REM = 4,
    OP_SUBPIECE = 5,
    OP_INT_DIV = 6,
    OP_INT_SLESS = 7,
    OP_LOAD = 8,
    OP_BRANCH = 9,
    OP_HALT = 10
} VM_Gen_3_bfaee9f8d108_opcode_t;

/* Formal pipeline stage sequence */
typedef enum {
    STAGE_0_STAGE_FETCH,
    STAGE_1_STAGE_DYNAMIC_DECRYPT,
    STAGE_2_STAGE_JUNK_NOOP,
    STAGE_3_STAGE_DECODE,
    STAGE_4_STAGE_JUNK_NOOP,
    STAGE_5_STAGE_OPERAND_FETCH,
    STAGE_6_STAGE_STAGE_MUTATOR,
    STAGE_7_STAGE_EXECUTE,
    STAGE_8_STAGE_COMMIT_WRITEBACK
} VM_Gen_3_bfaee9f8d108_stage_t;

/* Latches / Inter-stage register state */
typedef struct {
    uint32_t pc;
    uint64_t registers[16];
    uint64_t stack[64];
    uint32_t sp;
    uint32_t current_stage_idx;
    uint32_t entropy_key;
    bool halted;
} VM_Gen_3_bfaee9f8d108_context_t;

#endif /* VM_VM_GEN_3_BFAEE9F8D108_H */
