/* Auto-generated by c_mutatedStages Architecture Synthesizer */
/* Unique Architecture ID: VM_Gen_1_e02e36604372 */
/* Paradigm: HYBRID_STACK_REG | Dispatch: DISPATCH_STAGED_COROUTINE */

#ifndef VM_VM_GEN_1_E02E36604372_H
#define VM_VM_GEN_1_E02E36604372_H

#include <stdint.h>
#include <stdbool.h>

#define ARCH_ID "VM_Gen_1_e02e36604372"
#define PIPELINE_STAGE_COUNT 9

/* Opcodes for this polymorphic instance */
typedef enum {
    OP_INT_LEFT = 0,
    OP_BRANCHIND = 1,
    OP_INT_CARRY = 2,
    OP_STORE = 3,
    OP_HALT = 4,
    OP_INT_EQUAL = 5,
    OP_INT_SLESS = 6,
    OP_INT_SBORROW = 7,
    OP_INT_NOTEQUAL = 8,
    OP_SUBPIECE = 9,
    OP_LOAD = 10
} VM_Gen_1_e02e36604372_opcode_t;

/* Formal pipeline stage sequence */
typedef enum {
    STAGE_0_STAGE_FETCH,
    STAGE_1_STAGE_DYNAMIC_DECRYPT,
    STAGE_2_STAGE_DECODE,
    STAGE_3_STAGE_OPERAND_FETCH,
    STAGE_4_STAGE_EXECUTE,
    STAGE_5_STAGE_JUNK_NOOP,
    STAGE_6_STAGE_STAGE_MUTATOR,
    STAGE_7_STAGE_JUNK_NOOP,
    STAGE_8_STAGE_COMMIT_WRITEBACK
} VM_Gen_1_e02e36604372_stage_t;

/* Latches / Inter-stage register state */
typedef struct {
    uint32_t pc;
    uint64_t registers[16];
    uint64_t stack[64];
    uint32_t sp;
    uint32_t current_stage_idx;
    uint32_t entropy_key;
    bool halted;
} VM_Gen_1_e02e36604372_context_t;

#endif /* VM_VM_GEN_1_E02E36604372_H */
