/* Auto-generated by c_mutatedStages Architecture Synthesizer */
/* Unique Architecture ID: VM_Gen_1_79364899772a */
/* Paradigm: HYBRID_STACK_REG | Dispatch: DISPATCH_CALL_THREADED */

#ifndef VM_VM_GEN_1_79364899772A_H
#define VM_VM_GEN_1_79364899772A_H

#include <stdint.h>
#include <stdbool.h>

#define ARCH_ID "VM_Gen_1_79364899772a"
#define PIPELINE_STAGE_COUNT 6

/* Opcodes for this polymorphic instance */
typedef enum {
    OP_INT_MULT = 0,
    OP_INT_DIV = 1,
    OP_INT_LESS = 2,
    OP_CALL = 3,
    OP_HALT = 4,
    OP_STORE = 5,
    OP_INT_LESSEQUAL = 6,
    OP_SUBPIECE = 7,
    OP_INT_SCARRY = 8,
    OP_INT_ADD = 9,
    OP_INT_LEFT = 10
} VM_Gen_1_79364899772a_opcode_t;

/* Formal pipeline stage sequence */
typedef enum {
    STAGE_0_STAGE_FETCH,
    STAGE_1_STAGE_DYNAMIC_DECRYPT,
    STAGE_2_STAGE_DECODE,
    STAGE_3_STAGE_OPERAND_FETCH,
    STAGE_4_STAGE_EXECUTE,
    STAGE_5_STAGE_COMMIT_WRITEBACK
} VM_Gen_1_79364899772a_stage_t;

/* Latches / Inter-stage register state */
typedef struct {
    uint32_t pc;
    uint64_t registers[16];
    uint64_t stack[64];
    uint32_t sp;
    uint32_t current_stage_idx;
    uint32_t entropy_key;
    bool halted;
} VM_Gen_1_79364899772a_context_t;

#endif /* VM_VM_GEN_1_79364899772A_H */
