/* Auto-generated by c_mutatedStages Architecture Synthesizer */
/* Unique Architecture ID: VM_Gen_2_f56f8495e03d */
/* Paradigm: HYBRID_STACK_REG | Dispatch: DISPATCH_DIRECT_THREADED */

#ifndef VM_VM_GEN_2_F56F8495E03D_H
#define VM_VM_GEN_2_F56F8495E03D_H

#include <stdint.h>
#include <stdbool.h>

#define ARCH_ID "VM_Gen_2_f56f8495e03d"
#define PIPELINE_STAGE_COUNT 7

/* Opcodes for this polymorphic instance */
typedef enum {
    OP_CALL = 0,
    OP_INT_REM = 1,
    OP_HALT = 2,
    OP_INT_SCARRY = 3,
    OP_INT_CARRY = 4,
    OP_INT_XOR = 5,
    OP_INT_LEFT = 6,
    OP_INT_DIV = 7,
    OP_INT_RIGHT = 8,
    OP_INT_ADD = 9,
    OP_SUBPIECE = 10
} VM_Gen_2_f56f8495e03d_opcode_t;

/* Formal pipeline stage sequence */
typedef enum {
    STAGE_0_STAGE_FETCH,
    STAGE_1_STAGE_DYNAMIC_DECRYPT,
    STAGE_2_STAGE_DECODE,
    STAGE_3_STAGE_OPERAND_FETCH,
    STAGE_4_STAGE_EXECUTE,
    STAGE_5_STAGE_STAGE_MUTATOR,
    STAGE_6_STAGE_COMMIT_WRITEBACK
} VM_Gen_2_f56f8495e03d_stage_t;

/* Latches / Inter-stage register state */
typedef struct {
    uint32_t pc;
    uint64_t registers[16];
    uint64_t stack[64];
    uint32_t sp;
    uint32_t current_stage_idx;
    uint32_t entropy_key;
    bool halted;
} VM_Gen_2_f56f8495e03d_context_t;

#endif /* VM_VM_GEN_2_F56F8495E03D_H */
