/* Auto-generated by c_mutatedStages Architecture Synthesizer */
/* Unique Architecture ID: VM_Gen_2_edaa24118d43 */
/* Paradigm: STACK | Dispatch: DISPATCH_STAGED_COROUTINE */

#ifndef VM_VM_GEN_2_EDAA24118D43_H
#define VM_VM_GEN_2_EDAA24118D43_H

#include <stdint.h>
#include <stdbool.h>

#define ARCH_ID "VM_Gen_2_edaa24118d43"
#define PIPELINE_STAGE_COUNT 8

/* Opcodes for this polymorphic instance */
typedef enum {
    OP_I32_SHR_S = 0,
    OP_I32_EQ = 1,
    OP_I32_ROTL = 2,
    OP_I32_LT_S = 3,
    OP_I32_AND = 4,
    OP_I32_SHR_U = 5,
    OP_I32_LT_U = 6,
    OP_I32_XOR = 7,
    OP_I32_MUL = 8,
    OP_I32_ROTR = 9,
    OP_HALT = 10
} VM_Gen_2_edaa24118d43_opcode_t;

/* Formal pipeline stage sequence */
typedef enum {
    STAGE_0_STAGE_FETCH,
    STAGE_1_STAGE_DYNAMIC_DECRYPT,
    STAGE_2_STAGE_JUNK_NOOP,
    STAGE_3_STAGE_DECODE,
    STAGE_4_STAGE_STAGE_MUTATOR,
    STAGE_5_STAGE_OPERAND_FETCH,
    STAGE_6_STAGE_EXECUTE,
    STAGE_7_STAGE_COMMIT_WRITEBACK
} VM_Gen_2_edaa24118d43_stage_t;

/* Latches / Inter-stage register state */
typedef struct {
    uint32_t pc;
    uint64_t registers[16];
    uint64_t stack[64];
    uint32_t sp;
    uint32_t current_stage_idx;
    uint32_t entropy_key;
    bool halted;
} VM_Gen_2_edaa24118d43_context_t;

#endif /* VM_VM_GEN_2_EDAA24118D43_H */
