/* Auto-generated by c_mutatedStages Architecture Synthesizer */
/* Unique Architecture ID: Wasm_Staged_VM_2a302023b792 */
/* Paradigm: HYBRID_STACK_REG | Dispatch: DISPATCH_SWITCH */

#ifndef VM_WASM_STAGED_VM_2A302023B792_H
#define VM_WASM_STAGED_VM_2A302023B792_H

#include <stdint.h>
#include <stdbool.h>

#define ARCH_ID "Wasm_Staged_VM_2a302023b792"
#define PIPELINE_STAGE_COUNT 8

/* Opcodes for this polymorphic instance */
typedef enum {
    OP_INT_2COMP = 0,
    OP_BRANCH = 1,
    OP_HALT = 2,
    OP_INT_SEXT = 3,
    OP_INT_ZEXT = 4,
    OP_RETURN = 5,
    OP_INT_REM = 6,
    OP_INT_ADD = 7,
    OP_INT_SCARRY = 8,
    OP_INT_LEFT = 9,
    OP_LOAD = 10
} Wasm_Staged_VM_2a302023b792_opcode_t;

/* Formal pipeline stage sequence */
typedef enum {
    STAGE_0_STAGE_FETCH,
    STAGE_1_STAGE_JUNK_NOOP,
    STAGE_2_STAGE_DYNAMIC_DECRYPT,
    STAGE_3_STAGE_STAGE_MUTATOR,
    STAGE_4_STAGE_DECODE,
    STAGE_5_STAGE_OPERAND_FETCH,
    STAGE_6_STAGE_EXECUTE,
    STAGE_7_STAGE_COMMIT_WRITEBACK
} Wasm_Staged_VM_2a302023b792_stage_t;

/* Latches / Inter-stage register state */
typedef struct {
    uint32_t pc;
    uint64_t registers[16];
    uint64_t stack[64];
    uint32_t sp;
    uint32_t current_stage_idx;
    uint32_t entropy_key;
    bool halted;
} Wasm_Staged_VM_2a302023b792_context_t;

#endif /* VM_WASM_STAGED_VM_2A302023B792_H */
