/* Auto-generated by c_mutatedStages Architecture Synthesizer */
/* Unique Architecture ID: Wasm_Staged_VM_52578dd820f1 */
/* Paradigm: REGISTER | Dispatch: DISPATCH_SWITCH */

#ifndef VM_WASM_STAGED_VM_52578DD820F1_H
#define VM_WASM_STAGED_VM_52578DD820F1_H

#include <stdint.h>
#include <stdbool.h>

#define ARCH_ID "Wasm_Staged_VM_52578dd820f1"
#define PIPELINE_STAGE_COUNT 8

/* Opcodes for this polymorphic instance */
typedef enum {
    OP_BPF_NEG = 0,
    OP_BPF_OR = 1,
    OP_BPF_XOR = 2,
    OP_HALT = 3,
    OP_BPF_SUB = 4,
    OP_BPF_DIV = 5,
    OP_BPF_ARSH = 6,
    OP_BPF_MOV = 7,
    OP_BPF_LSH = 8,
    OP_BPF_END = 9,
    OP_BPF_AND = 10
} Wasm_Staged_VM_52578dd820f1_opcode_t;

/* Formal pipeline stage sequence */
typedef enum {
    STAGE_0_STAGE_FETCH,
    STAGE_1_STAGE_DYNAMIC_DECRYPT,
    STAGE_2_STAGE_DECODE,
    STAGE_3_STAGE_OPERAND_FETCH,
    STAGE_4_STAGE_JUNK_NOOP,
    STAGE_5_STAGE_STAGE_MUTATOR,
    STAGE_6_STAGE_EXECUTE,
    STAGE_7_STAGE_COMMIT_WRITEBACK
} Wasm_Staged_VM_52578dd820f1_stage_t;

/* Latches / Inter-stage register state */
typedef struct {
    uint32_t pc;
    uint64_t registers[16];
    uint64_t stack[64];
    uint32_t sp;
    uint32_t current_stage_idx;
    uint32_t entropy_key;
    bool halted;
} Wasm_Staged_VM_52578dd820f1_context_t;

#endif /* VM_WASM_STAGED_VM_52578DD820F1_H */
